### ISSUE TITLE
Research and Develop Add Media Feature

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#31]
Implementation methods for Media usage (e.g. video, audio) on the portal should be researched. A feasible solution should be implemented for the back-end.

**Comment by TalatCikikci** [comment]
Which media will be usable on the system? Proposed types are:

* [ ] Embed Video
* [ ] Upload Video
* [ ] Embed Audio
* [ ] Upload Audio
* [ ] Embed Pictures
* [ ] Upload Pictures
* [ ] Embed PDF/.doc/other
* [ ] Upload PDF/.doc/other

**Comment by barisaksan** [comment]
youtube + soundcloud + foto upload diyorum (dun foto da embed olsun dedim ama upload daha iyi sanki)

**Comment by barisaksan** [comment]
noembed free web service is used for creating embed tags. supported embed types according to noembed.com:

1.     Amazon
2.     iTunes Movie Trailers
3.     Ars Technica
4.     ASCII Art Farts
5.     Bash.org
6.     Beer Advocate
7.     Duffel Blog
8.     GiantBomb
9.     Gist
10.     Github Commit
11.     Gfycat
12.     IMDB
13.     Monoprice
14.     Spotify
15.     TED
16.     The Onion
17.     TrailerAddict
18.     Twitlonger
19.     Twitter
20.     Urban Dictionary
21.     Vimeo
22.     Vine
23.     Wikipedia
24.     XKCD
25.     YouTube
26.     Clyp
27.     Flickr
28.     Funny or Die
29.     GIFUK
30.     Hulu
31.     Qik
32.     Rdio
33.     SlideShare
34.     SoundCloud
35.     Viddler
36.     App.Net
37.     CloudApp
38.     Dropbox
39.     Imgur
40.     Imgur
41.     Instagram
42.     Lockerz
43.     Path
44.     Picplz
45.     Skitch
46.     Twitpic
47.     Twitter
48.     YFrog

**Comment by barisaksan** [comment]
We are officially supporting Instagram, Youtube and SoundCloud.
