### ISSUE TITLE
Decide on a Method to Integrate Time Selection

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#34]
System will require a creative way to add time for the heritage items since there is a large diversity of ways that a heritage item may possess a time attribute. For example it can be an exact date with hour resolution or it may be year BC.

Issue will be discussed here.

**Comment by TalatCikikci** [comment]
My proposal for the time selection page is as follows:

[[[images/AddHeritageTime.png]]](images/AddHeritageTime.png)

**Comment by erhan355** [comment]
As far as I understand , we don't need a date picker or something like that instead user enters date time manually .Right ?

**Comment by TalatCikikci** [comment]
I believe so; a datepicker is used to choose a date that is too specific for the purpose of a heritage item.

Heritage items may have the following as time properties;

- A year
- A year and a month
- A year, a month and a day
- A recurring event (every 22 of June) so a month and a day is also possible
- Between two specific dates (01 September 1939 - 02 September 1945)
- Between two months of a year (June - August 1994)
- Between two years (200 B.C. 4 A.D.)
- A specific date complete with hour (10 November 1938, 09.05)
...and a few more forms.

So if we use a datepicker we exclude some of these possibilities. I believe it would be better if we use a method other than datepicker. Best idea I can come up with so far for such a flexible time selection is to allow users enter whichever information is available without constraints.

**Comment by TalatCikikci** [comment]
According to the feedback that Ms. Uskudarli has given, we should also consider the case for decades.

For example; "80's", "90's", etc...

**Comment by TalatCikikci** [comment]
Mockups have been updated. Please check [mockups on Wiki Page](https://github.com/MergenGroup/ProjectMergen/wiki/Mockups#add-heritage-screens)

**Comment by erhan355** [comment]
I added to http://codepen.io/erhan355/pen/bpqKpQ. 
Waiting for feedback. before,I  push it into main project.

**Comment by erhan355** [comment]
Centruies added to master/origin

**Comment by erhan355** [comment]
All implementations have been done
