### ISSUE TITLE
Log Work - Koray

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#37]
Please log your effort spent on Mergen Projects tasks.

Create ***one comment for each week***, and log all that week's work under that comment by editing it.

Following format is sufficient:
```
Log for <weekMondayDate> - <weekSundayDate>:

* Worked on <theTaskDescription> - **<timeSpent>**
* Worked on <theTaskDescription> - **<timeSpent>**
...
```

*These logs will help us create a weekly report on our progress so make sure you have logged your weekly effort until Sunday EoD!*

**Comment by barisaksan** [comment]
Log for 21-03-2016 - 27-03-2016:

* Worked on Linked Data research and Jena integration - **6**
* Code review and bug fix - **2**

**Comment by koraytugay** [comment]
Log for 24-04-2016

- Worked on linking our own tags to dbpedia tags and search functionality. - 6 hours
