### ISSUE TITLE
User Story - Login

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#50]
Login functionality will be implemented.

Login requirement specification can be found here: [Login](https://github.com/MergenGroup/ProjectMergen/wiki/Requirements#req-14-login)

**Comment by TalatCikikci** [comment]
**CURRENT TODO**

- [ ] User should stay signed in after sign-up process.
- [ ] A message should be displayed for incorrect login attempt.

**Comment by TalatCikikci** [comment]
@koraytugay ; please don't forget to mark the checkbox after implementation is done for the issue #78

**Comment by koraytugay** [comment]
done long time ago.
