### ISSUE TITLE
User Story - Edit Account

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#51]
Edit Account functionality will be implemented.

Edit Account requirement specification can be found here: [Edit Account](https://github.com/MergenGroup/ProjectMergen/wiki/Requirements#req-18-edit-account)

**Comment by TalatCikikci** [comment]
**CURRENT TODO**
- [ ] Saves profile images as ".jpg" files. Should to support other files types like png etc... ( #79 )

**Comment by koraytugay** [comment]
this is not a bug. we support only jpg files.
