### ISSUE TITLE
User Story - Create Heritage

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#52]
Create Heritage functionality will be implemented.

Create Heritage requirement specification can be found here: [Create Heritage](https://github.com/MergenGroup/ProjectMergen/wiki/Requirements#req-21-add-new-heritage-item)

**Comment by TalatCikikci** [comment]
**CURRENT TODOS**
- [ ] Heritage item cateogries need to be implemented.

**Comment by koraytugay** [comment]
this is done, continue with sub tasks.
