### ISSUE TITLE
User Story - Heritage Time Selection

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#54]
Heritage Time Selection functionality will be implemented.

Heritage Time Selection requirement specification can be found here: [Heritage Time Selection](https://github.com/MergenGroup/ProjectMergen/wiki/Requirements#req-24-heritage-item-time-selection-and-display)

**Comment by TalatCikikci** [comment]
**CURRENT TODOS***
- [ ] Heritage time selection should be able to have "reccuring events".

**Comment by erhan355** [comment]
It has been implemented
