### ISSUE TITLE
User Story - Semantic Tags

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#56]
Semantic Tags - Query global data functionality will be implemented in sprint 3.
Semantic Tags - Auto complete functionality while the tag is being typed will be implemented in sprint 3.

Semantic Tags requirement specification can be found here: [Semantic Tags](https://github.com/MergenGroup/ProjectMergen/wiki/Requirements#req-26-semantic-tags)

**Comment by erhan355** [comment]
It has been implemented
