### ISSUE TITLE
My Profile Page Saves Avatars With ".jpg" Extension

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#79]
Profile picture saves images as ".jpg" files, even if they are in another format.

**Reproduction Steps:**
1. User clicks "Choose File".
2. User selects a ".png" file.
3. User clicks "Submit".

![image](https://cloud.githubusercontent.com/assets/16108843/14944568/932a8976-0fff-11e6-8509-79bf14c7bd39.png)

Related to user story #51

**Comment by koraytugay** [comment]
not a bug
