### ISSUE TITLE
My Profile Page Returns "String Index Out Of Range" Error on Submit

### ISSUE THREAD

**Issue by TalatCikikci** [MergenGroup/ProjectMergen#80]
Independent of the status of the fields, My Profile page gives a "Sting index out of range" error when the user clicks on the submit button.

Following conditions are tested and the issue occurs on all of them:
- No changes on page
- Only added a profile avatar
- Only added a single word user name
- Only added a user name with multiple words
- Only checked the privacy checkbox
- Added an avatar, added a single word username and checked the privacy checkbox.

Related to use case: ( #51 )

**Error Log**

Oops!
Failed URL: http://localhost:8084/profile/updateProfile
Sorry, an error has occured String index out of range: -1
java.lang.String.substring(String.java:1960)> heritage.mergen.web.ProfileController.updateOwnProfile(ProfileController.java:53)> sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)> sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)> java.lang.reflect.Method.invoke(Method.java:497)> org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)> org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)> org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)> org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)> org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)> org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)> org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)> org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)> org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)> org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)> javax.servlet.http.HttpServlet.service(HttpServlet.java:644)> org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)> javax.servlet.http.HttpServlet.service(HttpServlet.java:725)> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)> org.netbeans.modules.web.monitor.server.MonitorFilter.doFilter(MonitorFilter.java:393)> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)> org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)> org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)> org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)> org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)> org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)> org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)> org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)> org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)> org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)> org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)> org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)> org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)> org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)> org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)> org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)> org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)> org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)> org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)> java.lang.Thread.run(Thread.java:745)>

**Comment by koraytugay** [comment]
fixed.
