### ISSUE TITLE
Duplicate comment 

### ISSUE THREAD

**Issue by uskudarli** [MergenGroup/ProjectMergen#83]
I entered a comment on the Anastasian Wall heritage item.

http://mergenheritage.duckdns.org/heritage/showHeritage/7

The comment shows duplicate.

[  I have seen the Anastasian Wall. It is not so easy to find, very few parts of it remain. But, really exciting to see. Italian architects have been working hard on preserving it. Hopefully Turkish officials will also show same reverence in preserving much of the damaged wall.
uskudarli2@gmail.com - 2016-05-30 23:22 ]

In previous demos, I have seen it in triplicates. No idea what is going on. But needs to be traced.

**Comment by koraytugay** [comment]
Fixed.

**Comment by koraytugay** [comment]
Existing multiple comments should be deleted from db manually.

**Comment by koraytugay** [comment]
"Existing multiple comments should be deleted from db manually." -> This is fixed as well.
