### ISSUE TITLE
Liking a heritage did not increase count

### ISSUE THREAD

**Issue by uskudarli** [MergenGroup/ProjectMergen#84]
I liked http://mergenheritage.duckdns.org/heritage/showHeritage/7

The button became red, but the count did not increase.

I logged in with a new user uskudarli2@gmail.com

**Comment by koraytugay** [comment]
When you like a heritage text changes from 
0 people liked.
to
You and 0 people liked.
which is fine.
Login with a different user and go to same heritage, you will see: 1 people liked. Like with this new user and you will see: You and 1 people liked.
