### ISSUE TITLE
Edit location is not permitted

### ISSUE THREAD

**Issue by uskudarli** [MergenGroup/ProjectMergen#86]
I tried to change the location. But could not select and move the Marker.

When I placed marker initially it was too close maybe. The map shows far too close and useless. I wanted to edit it to zoom out.

I tried replacing the marker and zooming out. Neither worked.

Should be able to edit marker location as well as zoom level.

**Comment by barisaksan** [comment]
To move a marker on the map while editing the heritage, the user needs to:
- press the edit button on the map,
- drag and drop the marker to new location
- press the save button on the map

Zoom level is arranged to the closest zoom level which can display all the location markers.

**Comment by barisaksan** [comment]
with commit 63562b7 zoom levels and map bounds are saved for heritage locations.

**Comment by uskudarli** [comment]
thanks. 

Nice :)
