### ISSUE TITLE
Labels and Heritage Categories are not showing up

### ISSUE THREAD

**Issue by uskudarli** [MergenGroup/ProjectMergen#87]
I created a new heritage:

http://mergenheritage.duckdns.org/heritage/showHeritage/12

I have added several tags (I found nice semantic contexts for all of them). But they do not show up on my heritage.

I added (tying to remember....)
michelangelo (michelangelo)
medici family (medici house)
florence( florence italy)
Laurentian Library (Laurentian Library )

at least.

I tried another time to repeat -- this time only michelangelo
does not work.

**Comment by koraytugay** [comment]
@barisaksan Please execute the statements in mysql in duckdns:

ALTER TABLE tag MODIFY tag_category VARCHAR(6000);
ALTER TABLE tag MODIFY tagUri VARCHAR(6000);

**Comment by barisaksan** [comment]
done

**Comment by uskudarli** [comment]
I tried to add labels again... No luck! Same problem. They do not show up!

Tried Michelangelo and Medici ... After I save, I do not see them. I am expecting to see them, is there something I am missing?

**Comment by koraytugay** [comment]
@uskudarli that was a different problem actually. while editing heritages, adding tags were not supported. should be fixed now. duckdns will be updated in 5 - 10 minutes. closing again.

**Comment by koraytugay** [comment]
@uskudarli I edited heritage and added a label to: http://mergenheritage.duckdns.org/heritage/showHeritage/12 . seems to work fine.

**Comment by uskudarli** [comment]
Just tried it. Works fine.

Now all I need is a compliment on my wonderful content:

It does look gorgeous :+1:  -- Nicely done people.

![screenshot from 2016-06-01 20 24 14](https://cloud.githubusercontent.com/assets/1347035/15719059/d911cb80-2836-11e6-990d-206ab556c121.png)
![screenshot from 2016-06-01 20 23 50](https://cloud.githubusercontent.com/assets/1347035/15719060/d923e6bc-2836-11e6-8952-7aa1aa6680b2.png)
